name: savedesktop
grade: stable
adopt-info: savedesktop
license: GPL-3.0+

base: core22
confinement: strict

slots:
  gnome-dbus:
    interface: dbus
    bus: session
    name: org.gnome.SessionManager
  xfce-dbus:
    interface: dbus
    bus: session
    name: org.xfce.SessionManager
  kde-dbus:
    interface: dbus
    bus: session
    name: org.kde.ksmserver

apps:
  savedesktop:
    extensions: [gnome]
    command: usr/bin/savedesktop.sh
    desktop: usr/share/applications/io.github.vikdevelop.SaveDesktop.desktop
    common-id: io.github.vikdevelop.SaveDesktop.desktop
    plugs:
      - gsettings
      - home
      - network
    environment:
      HOME: $SNAP_REAL_HOME

parts:
  savedesktop-necessary:
    source: https://github.com/vikdevelop/SaveDesktop/releases/download/2.9.8_snap2/savedesktop-snapcraft-necessary-files.zip
    plugin: dump
  dconf:
    source: https://github.com/vikdevelop/SaveDesktop/releases/download/2.9.5n/dconf_build.tar.xz
    plugin: dump
  savedesktop:
    source: https://github.com/vikdevelop/SaveDesktop/archive/refs/tags/2.9.8_snap2.tar.gz
    plugin: dump
    parse-info: [flatpak/io.github.vikdevelop.SaveDesktop.metainfo.xml]
    stage-packages:
       - wget
       - libnotify-bin
