name: Bug report
description: Report a bug of SaveDesktop app to developer
title: "bug:"
labels: [bug]
body:
  - type: input
    id: distro
    attributes:
      label: Linux distribution
      description: "Write the name and version of Linux distribution"
      placeholder: "e.g. Fedora 37, Ubuntu 22.04"
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Desktop Environment
      description: |
        What Desktop Environment are you using?
      options:
        - Select
        - GNOME
        - KDE Plasma
        - Xfce
        - Cinnamon
        - MATE
        - Pantheon (elementaryOS)
        - Budgie
        - COSMIC (Pop!_OS)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SaveDesktop version
      description: "You can find it by clicking on the three dots and then the "About app" button"
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Package type
      description: |
        How did you install SaveDesktop?
      options:
        - Flatpak from Flathub
        - Flatpak, which was built with Flatpak Builder
        - Native version
        - Snap package
    validations:
      required: true
  - type: textarea
    id: bugdesc
    attributes:
      label: Bug description
      description: Describe the problem, steps to reproduce, alternatively insert output from the terminal
    validations:
      required: true
