name: Feature request
description: Suggestion to improve SaveDesktop
title: "feature_request: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: The current problem or need
      description: 
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Describe the solution you'd like
      description: 
    validations:
      required: true
