name: Question
description: Do you have any questions related to the SaveDesktop app, the Github wiki, or something similar?
title: "question: "
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: 
    validations:
      required: true
